lib/device/library/linux.rb

Ubuntu 16.04 では Kindle のマウントポイントの場所が `/media/OSユーザー名/Kindle` 
となっています。一方、send コマンドが調べるマウントポイントは `/media/Kindle`
と `/mnt/Kindle` のみでした。
そこで、 `/media/OSユーザー名/Kindle` も調べるように修正しました。

Ubuntu 16.04 で send コマンドが動くように修正

---

lib/web/appserver.rb

インターネットへ繋いでない状態で `narou web` を実行すると以下のように失敗しました。
```shell
$ narou web -n
/home/kubo/local/ruby64-2.2.2/lib/ruby/gems/2.2.0/gems/narou-2.9.5/lib/web/appserver.rb:193:in `connect': Network is unreachable - connect(2) for "128.0.0.0" port 7 (Errno::ENETUNREACH)
```
IPアドレスの割り当てられているNICはいくつもあるのですが、以下のように default route が
設定されてないため 128.0.0.0 への送信に使用できる NIC が見付からず、 `Errno::ENETUNREACH`
例外があがります。
```shell
$ route -n
カーネルIP経路テーブル
受信先サイト    ゲートウェイ    ネットマスク   フラグ Metric Ref 使用数 インタフェース
10.0.3.0        0.0.0.0         255.255.255.0   U     0      0        0 lxcbr0
169.254.0.0     0.0.0.0         255.255.0.0     U     1000   0        0 enp0s31f6
172.16.42.0     0.0.0.0         255.255.255.0   U     0      0        0 vmnet8
172.16.78.0     0.0.0.0         255.255.255.0   U     0      0        0 vmnet1 …
```

128.0.0.0 へのルーティングがないと narou web が起動しない問題の修正

---

lib/device/library/linux.rb

Ubuntu 以外の udisks2 を使っている Linux は `/run/media/ユーザー名/Kindle` に
Kindle をマウントするようなので、 `/run/media/ユーザー名` も見るようにしました。
udisks2 はデフォルトでは `/run/media/ユーザー名` を使い、
Ubuntu はカスタマイズして `/media/ユーザー名` にしているようです。

Ubuntu 以外の udisks2 を使っている Linux でも send コマンドが動くように修正

---

lib/narou.rb

3.0.1でnarou.rbを初期設定しようとすると以下のエラーが出て終了しました。
> $ narou init
> /var/lib/gems/2.3.0/gems/narou-3.0.1/lib/narou.rb:95:in `init': uninitialized constant #<Class:Narou>::LOCAL_SETTING_DIR (NameError)
>   エラーが発生したため終了しました。
>   詳細なエラーは --backtrace オプションを付けて再度実行して下さい。
定数名を修正したところ、初期設定できるようになりました。

fix: narou initを実行すると落ちる

---

lib/converterbase.rb

「`.`」の前後の数字の種類をチェックして、同じ種類の時のみ小数とみなすようにしました。
以下のようなordered listが小数と誤認識されるのを回避できるようになるはずです。
```
1.一石二鳥
```

fix convert numbers

---

lib/command/init.rb

https://github.com/whiteleaf7/narou/pull/167#issuecomment-299682953 で指摘された問題と、別途発見した問題を修正しました。修正内容は以下の通りです。すみませんが、確認の上、マージをお願いします。
- ask_aozoraepub3_path関数の戻り値を使っていませんでした。orと=の優先度を間違えていました
- `narou init -p :keep`が動作していない問題を解決しました。この後の処理で`:keep`を確認していると勘違いしていました
- ディレクトリチェックしていない問題。これも`:keep`と同様に勘違いしていました
- グローバル設定がないまったくの初回に:keep の場合はこんな感じでしょうか
```
$ narou init -p :keep
------------------------------
AozoraEpub3の設定を行います
!!!WARNING!!!                             
AozoraEpub3の構成ファイルを書き換えます。narouコマンド用に別途新規インストールしておくことをオススメします
指定されたフォルダにAozoraEpub3がありません。
AozoraEpub3のあるフォルダを入力して下さい:
(未入力でスキップ)
>:keep
入力されたフォルダにAozoraEpub3がありません。もう一度入力して下さい:
>
設定をスキップしました。あとで narou init で再度設定出来ます
初期化が完了しました！
現在のフォルダ下で各種コマンドが使用出来るようになりました。
まずは narou help で簡単な説明を御覧ください。
```

Fix problems introduced #167

---

lib/converterbase.rb

`insert_separate_space` で感嘆符・疑問符の後にスペースが入るので、
`convert_novel_rule` の誤字対策が機能していませんでした。

感嘆符・疑問符直後の句読点についての補正が機能していなかったのを修正

---

lib/novelconverter.rb
lib/novelsetting.rb

[銀河連合日本](http://ncode.syosetu.com/n5084bv/)のファイル名が
```
[_本保羽] 銀河連合日本.txt
```
となるのが悲しい感じで、update コマンドには `-o` オプションもないので、`setting.ini` で指定できるようにしてみました。
ついでにタイトルや著者名に手を入れる手段が見当たらなかったので、こちらも指定できるようにしてみました。
例えば、[スライムなダンジョンで天下をとろうと思う（再掲載）](http://ncode.syosetu.com/n3782bu/)の「（再掲載）」の部分はいらないので。

setting.iniで色々指定できるように

---

narou.gemspec

mail 2.6.6が、mail 2.7.0に更新されてから、以下のエラーが出るようになっていたので修正です。
```
$ narou m
...
[ERROR] undefined method `delivery_method' for Pony:Module
```
取り敢えず、mailを2.6.Xを使うよう指定しました。

メールが送れなくなっていた件の修正

---

lib/novelconverter.rb

#232 の修正です。以前の修正に間違いがありました。
```
$ narou s force.enable_inspect=true
$ narou c n7975cr
ID:46　蜘蛛ですが、なにか？ の変換を開始
小説状態の調査結果を 調査ログ.txt に出力しました（エラー：6件、警告：0件、INFO：1件）
縦書用の変換が終了しました
AozoraEpub3でEPUBに変換しています.....変換しました
kindlegen実行中...........................変換しました
kindlestrip実行中
[馬場翁] 蜘蛛ですが、なにか？.mobi を出力しました
MOBIファイルを出力しました
```

inspect関連のバグ修正

---

spec/device_spec.rb

Windows 7 でなくても (Windows 10 であっても) RSpec が通るように変更。

Allow "Windows10_OS" or "Windows" as drive label

---

lib/commandline.rb

avoid encoding when arg is an Integer instance

---

lib/helper.rb

改変の参考記事:「[暗黙的にハッシュオブジェクトをキーワード引数に変換している場合](https://qiita.com/jnchito/items/c15ac23791e0320e0fc2#%E8%AA%AC%E6%98%8E%E3%81%9D%E3%81%AE1%E6%9A%97%E9%BB%99%E7%9A%84%E3%81%AB%E3%83%8F%E3%83%83%E3%82%B7%E3%83%A5%E3%82%AA%E3%83%96%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%82%92%E3%82%AD%E3%83%BC%E3%83%AF%E3%83%BC%E3%83%89%E5%BC%95%E6%95%B0%E3%81%AB%E5%A4%89%E6%8F%9B%E3%81%97%E3%81%A6%E3%81%84%E3%82%8B%E5%A0%B4%E5%90%88)」

avoid last argument as keyword parameters

---

lib/sitesetting.rb

私の手元の Ruby 2.7 はこの改変でうまく動作しているように見えますが、他の環境は未検証です。

avoid nul-separated glob pattern

---

.rubocop.yml

この修正をしないと、rubocop 実行時に大量の warning が出ます。([参考記事](https://stackoverflow.com/questions/58218587/how-to-disable-warning-no-department-given-for-cop-message-on-running-rubocop))

fill department names in .rubocop.yml

---

lib/converterbase.rb
lib/downloader.rb
lib/illustration.rb

Rubocop における以下の説明に従って、手動で修正しました。(Rubocop の auto-correct を用いた自動修正は、まだ動作が怪しくて今回未使用です。)
https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/UriRegexp
一応、RSpec も全部通るように見えます (Windows 10)。

URI.regexp → URI::DEFAULT_PARSER.make_regexp

---

lib/novelconverter.rb

misspell (tempalte -> template)

---

.rubocop.yml

Ruby 2.7 から該当する括弧が意味を持つようになり、RuboCop 0.80.1 から削除されました。 
これに合わせ、こちらの .rubocop からも削除しました。(残ったままだと、RuboCop は error を出します。)

remove `Style/BracesAroundHashParameters` cop

---

lib/downloader.rb

手元にあるリストを入力し、連続でダウンロードを実行する際に、連続して削除された小説があった場合にウェイトが無いとアクセス制限がかかり、10分程度待った上で手動で再試行する必要がありました。
削除されていた場合にもウェイトを入れている場合は100件程度をまとめて入力した場合にもこの問題は発生しませんでした。

404の場合でもウェイトを挟む

---

lib/command/tag.rb
lib/converterbase.rb

通常の実行には問題ありませんが、-W2 を付けて実行すると警告が出るので、以下の点を修正しました。
* lib/command/tag.rb (15行目、`'` が2回出現しているため1つ削除)
* lib/converterbase.rb (18行目、[`_` は `\w` に含まれる](https://docs.ruby-lang.org/ja/latest/doc/spec=2fregexp.html#string)ため削除)
Ruby 3.1.2 上では RSpec を実行して `875 examples, 0 failures, 2 pending` でした。

fix "duplicated range"

---

lib/converterbase.rb

「小説家になろう」のルビタグ｜（）≪≫が混在する場合の変換ミスを修正しました。
現行だと
```
入力: "｜朝（あさ）と夜≪よる≫"
出力: "｜｜朝《あさ》と夜《よる》"
```
となるのを
`出力: "｜朝《あさ》と｜夜《よる》"`
となるように直しました。
[ルビの（　）と《　》が同一行に混じってかつ｜があると正しく処理されない\#155](https://github.com/whiteleaf7/narou/issues/155)
に対応したつもりです。
確認のため、簡単なテストコードを作成しました。
参考までに貼り付けさせて頂きます。
[test_narou_ruby.zip](https://github.com/whiteleaf7/narou/files/14298801/test_narou_ruby.zip)

なろうルビタグの変換バグを修正

---

lib/command/setting.rb
lib/extension.rb

command/setting.rb へのUser-Agent 設定の追加と
有志による extension.rb の make_open_uri_options での add.merge 修正案に
User-Agent 設定を読み込ませる為
inventoryの読み込みと、適当な初期値を加えました

User-Agen 設定の追加

---

lib/downloader.rb
webnovel/ncode.syosetu.com.yaml
webnovel/novel18.syosetu.com.yaml

小説家になろう目次ページの分割への対応
修正しました。
~~念のため無限ループ対策として最大100ページまでに制限してます。~~
プログレスバーの付加にあわせて全ページ数を取得するようにしました。
~~そこまで必要かわかりませんでしたが、念のため、`toc_url`は毎回ループ前の値に復帰しています。~~
別メソッド分離にあわせて、メソッド終了時に復帰するようにしました。

Pagination support; 小説家になろう目次ページの分割への対応

---

lib/command/update/general_lastup_updater.rb
lib/downloader.rb

Ruby3.2以降、入出力で`IO::TimeoutError`が発生する可能性がある。
`OpenURI::HTTPError`他、エラー処理している3ヶ所について、`IO::TimeoutError`も加えた。
なお、3.1以前では未定義になるので`ダミーのIO::TimeoutError`を定義している。

fix: IO::TimeoutError for ruby 3.2 or later (ruby Feature #18630)

---

lib/command/diff.rb
lib/helper.rb
lib/novelconverter.rb

いくつかまとめてプルリクします。
/api/diff_clean で`CommandLine.run!`に`Integer`が渡されているが、ruby3.2より`Object#=~`が削除されたため`Integer#=~`がNoMethodErrorとなる
いったんto_sでStringにして処理する
レアケースだが、小説の保存フォルダが消えている場合、`get_sorted_cache_list`がnilを返すためNoMethodErrorとなる
empty?ではなくactivesupportのblank?を使う
小説タイトルにglobのワイルドカードである「[]{}」があるとdiffで`Dir.glob`が期待したリストを返さず、差分が表示されないなどの不具合が発生する
template/OPS/fontsが無い場合、フォントがコピーされないのでコピー前にディレクトリを作る
`FileUtils.mkdir_p`は存在を確認するので、事前にディレクトリの有無はチェックしない

Fix a few bug
